### ISSUE TITLE
Failed to load the angular-2 package

### ISSUE THREAD

**Issue by aliz1369** [madhusudhand/atom-angular2#13]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.15.0 x64
**Electron**: 1.3.13
**OS**: Mac OS X 10.12.4
**Thrown From**: [angular-2](https://github.com/madhusudhand/atom-angular2) package 0.2.6

### Stack Trace

Failed to load the angular-2 package

```
At Cannot find module 'js-module-indexer'

Error: Cannot find module 'js-module-indexer'
    at Module._resolveFilename (module.js:455:15)
    at Module._resolveFilename (/Applications/Atom.app/Contents/Resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._resolveFilename (/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/Users/AliZ/Desktop/angular/aliz/atom-angular2/lib/autocomplete/indexer.js:5:17)
    at Module._compile (/app.asar/src/native-compile-cache.js:109:30)
    at /app.asar/src/compile-cache.js:216:21)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/Users/AliZ/Desktop/angular/aliz/atom-angular2/lib/autocomplete/provider.js:6:17)
    at Module._compile (/app.asar/src/native-compile-cache.js:109:30)
    at /app.asar/src/compile-cache.js:216:21)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/Users/AliZ/Desktop/angular/aliz/atom-angular2/lib/index.js:6:29)
    at Module._compile (/app.asar/src/native-compile-cache.js:109:30)
    at /app.asar/src/compile-cache.js:216:21)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (/app.asar/src/native-compile-cache.js:50:27)
```

### Commands

```
```

### Non-Core Packages

```
angular-2 0.2.6 
atom-typescript 10.1.15 
linter 1.11.23 
```

**Comment by narayanmp** [comment]
Any fix for this?
